// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: items.sql

package db

import (
	"context"
	"database/sql"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    id, slug, name, text, is_completed, priority, tags, categories
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, slug, name, text, is_completed, priority, tags, categories, created_at, updated_at
`

type CreateItemParams struct {
	ID          string         `json:"id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Text        sql.NullString `json:"text"`
	IsCompleted bool           `json:"is_completed"`
	Priority    string         `json:"priority"`
	Tags        sql.NullString `json:"tags"`
	Categories  string         `json:"categories"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Text,
		arg.IsCompleted,
		arg.Priority,
		arg.Tags,
		arg.Categories,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Text,
		&i.IsCompleted,
		&i.Priority,
		&i.Tags,
		&i.Categories,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items WHERE id = ?
`

func (q *Queries) DeleteItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteItem, id)
	return err
}

const getAllItems = `-- name: GetAllItems :many
SELECT id, slug, name, text, is_completed, priority, tags, categories, created_at, updated_at FROM items ORDER BY created_at DESC
`

func (q *Queries) GetAllItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getAllItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Text,
			&i.IsCompleted,
			&i.Priority,
			&i.Tags,
			&i.Categories,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItem = `-- name: GetItem :one
SELECT id, slug, name, text, is_completed, priority, tags, categories, created_at, updated_at FROM items 
WHERE slug = ? AND json_extract(categories, '$[0]') = ? LIMIT 1
`

type GetItemParams struct {
	Slug       string `json:"slug"`
	Categories string `json:"categories"`
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, arg.Slug, arg.Categories)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Text,
		&i.IsCompleted,
		&i.Priority,
		&i.Tags,
		&i.Categories,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, slug, name, text, is_completed, priority, tags, categories, created_at, updated_at FROM items WHERE id = ? LIMIT 1
`

func (q *Queries) GetItemByID(ctx context.Context, id string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Text,
		&i.IsCompleted,
		&i.Priority,
		&i.Tags,
		&i.Categories,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemTree = `-- name: GetItemTree :many
SELECT 
    json_extract(categories, '$[0]') as category,
    json_group_array(
        json_object(
            'id', id,
            'slug', slug,
            'name', name,
            'text', text,
            'isCompleted', is_completed,
            'priority', priority,
            'tags', json(tags),
            'categories', json(categories),
            'createdAt', created_at,
            'updatedAt', updated_at
        )
    ) as items
FROM items
GROUP BY json_extract(categories, '$[0]')
ORDER BY category
`

type GetItemTreeRow struct {
	Category interface{} `json:"category"`
	Items    interface{} `json:"items"`
}

func (q *Queries) GetItemTree(ctx context.Context) ([]GetItemTreeRow, error) {
	rows, err := q.db.QueryContext(ctx, getItemTree)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemTreeRow
	for rows.Next() {
		var i GetItemTreeRow
		if err := rows.Scan(&i.Category, &i.Items); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsByCategory = `-- name: GetItemsByCategory :many
SELECT id, slug, name, text, is_completed, priority, tags, categories, created_at, updated_at FROM items 
WHERE json_extract(categories, '$[0]') = ?
ORDER BY created_at DESC
`

func (q *Queries) GetItemsByCategory(ctx context.Context, categories string) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getItemsByCategory, categories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Text,
			&i.IsCompleted,
			&i.Priority,
			&i.Tags,
			&i.Categories,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET 
    name = COALESCE(?2, name),
    slug = COALESCE(?3, slug),
    text = COALESCE(?4, text),
    is_completed = COALESCE(?5, is_completed),
    priority = COALESCE(?6, priority),
    tags = COALESCE(?7, tags),
    categories = COALESCE(?8, categories)
WHERE id = ?
RETURNING id, slug, name, text, is_completed, priority, tags, categories, created_at, updated_at
`

type UpdateItemParams struct {
	Name        sql.NullString `json:"name"`
	Slug        sql.NullString `json:"slug"`
	Text        sql.NullString `json:"text"`
	IsCompleted sql.NullBool   `json:"is_completed"`
	Priority    sql.NullString `json:"priority"`
	Tags        sql.NullString `json:"tags"`
	Categories  sql.NullString `json:"categories"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, updateItem,
		arg.Name,
		arg.Slug,
		arg.Text,
		arg.IsCompleted,
		arg.Priority,
		arg.Tags,
		arg.Categories,
		arg.ID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Text,
		&i.IsCompleted,
		&i.Priority,
		&i.Tags,
		&i.Categories,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
