// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: collections.sql

package db

import (
	"context"
	"database/sql"
)

const addTrackToCollection = `-- name: AddTrackToCollection :one
INSERT INTO collection_tracks (id, collection_id, track_id)
VALUES (?, ?, ?)
RETURNING id, collection_id, track_id, added_at
`

type AddTrackToCollectionParams struct {
	ID           string `json:"id"`
	CollectionID string `json:"collection_id"`
	TrackID      string `json:"track_id"`
}

func (q *Queries) AddTrackToCollection(ctx context.Context, arg AddTrackToCollectionParams) (CollectionTrack, error) {
	row := q.db.QueryRowContext(ctx, addTrackToCollection, arg.ID, arg.CollectionID, arg.TrackID)
	var i CollectionTrack
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.TrackID,
		&i.AddedAt,
	)
	return i, err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (id, name, description, tags, state)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, description, tags, state, created_at, updated_at
`

type CreateCollectionParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Tags        sql.NullString `json:"tags"`
	State       string         `json:"state"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, createCollection,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.State,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = ?
`

func (q *Queries) DeleteCollection(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCollection, id)
	return err
}

const getCollection = `-- name: GetCollection :one
SELECT id, name, description, tags, state, created_at, updated_at FROM collections WHERE id = ? LIMIT 1
`

func (q *Queries) GetCollection(ctx context.Context, id string) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollection, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectionTracks = `-- name: GetCollectionTracks :many
SELECT t.id, t.song_id, t.source_type, t.file_path, t.suno_id, t.udio_id, t.image_path, t.title, t.duration_ms, t.style_desc, t.rating, t.is_trash, t.is_deleted, t.artist_tags, t.album_tags, t.genre_tags, t.mood_tags, t.tags, t.metadata, t.created_at, t.updated_at FROM tracks t
JOIN collection_tracks ct ON ct.track_id = t.id
WHERE ct.collection_id = ?
ORDER BY ct.added_at DESC
`

func (q *Queries) GetCollectionTracks(ctx context.Context, collectionID string) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, getCollectionTracks, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.SongID,
			&i.SourceType,
			&i.FilePath,
			&i.SunoID,
			&i.UdioID,
			&i.ImagePath,
			&i.Title,
			&i.DurationMs,
			&i.StyleDesc,
			&i.Rating,
			&i.IsTrash,
			&i.IsDeleted,
			&i.ArtistTags,
			&i.AlbumTags,
			&i.GenreTags,
			&i.MoodTags,
			&i.Tags,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrackCollections = `-- name: GetTrackCollections :many
SELECT c.id, c.name, c.description, c.tags, c.state, c.created_at, c.updated_at FROM collections c
JOIN collection_tracks ct ON ct.collection_id = c.id
WHERE ct.track_id = ?
`

func (q *Queries) GetTrackCollections(ctx context.Context, trackID string) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, getTrackCollections, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isTrackInAnyCollection = `-- name: IsTrackInAnyCollection :one
SELECT EXISTS(
    SELECT 1 FROM collection_tracks WHERE track_id = ?
) AS in_collection
`

func (q *Queries) IsTrackInAnyCollection(ctx context.Context, trackID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, isTrackInAnyCollection, trackID)
	var in_collection int64
	err := row.Scan(&in_collection)
	return in_collection, err
}

const listCollections = `-- name: ListCollections :many
SELECT id, name, description, tags, state, created_at, updated_at FROM collections ORDER BY name ASC
`

func (q *Queries) ListCollections(ctx context.Context) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTrackFromCollection = `-- name: RemoveTrackFromCollection :exec
DELETE FROM collection_tracks WHERE collection_id = ? AND track_id = ?
`

type RemoveTrackFromCollectionParams struct {
	CollectionID string `json:"collection_id"`
	TrackID      string `json:"track_id"`
}

func (q *Queries) RemoveTrackFromCollection(ctx context.Context, arg RemoveTrackFromCollectionParams) error {
	_, err := q.db.ExecContext(ctx, removeTrackFromCollection, arg.CollectionID, arg.TrackID)
	return err
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections
SET
  name = COALESCE(?1, name),
  description = COALESCE(?2, description),
  tags = COALESCE(?3, tags),
  state = COALESCE(?4, state)
WHERE id = ?5
RETURNING id, name, description, tags, state, created_at, updated_at
`

type UpdateCollectionParams struct {
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Tags        sql.NullString `json:"tags"`
	State       sql.NullString `json:"state"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, updateCollection,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.State,
		arg.ID,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
