// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ideas.sql

package db

import (
	"context"
	"database/sql"
)

const createIdea = `-- name: CreateIdea :one
INSERT INTO ideas (id, name, project_id, description, tags, state, reference_notes)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, project_id, description, tags, state, reference_notes, created_at, updated_at
`

type CreateIdeaParams struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	ProjectID      string         `json:"project_id"`
	Description    sql.NullString `json:"description"`
	Tags           sql.NullString `json:"tags"`
	State          string         `json:"state"`
	ReferenceNotes sql.NullString `json:"reference_notes"`
}

func (q *Queries) CreateIdea(ctx context.Context, arg CreateIdeaParams) (Idea, error) {
	row := q.db.QueryRowContext(ctx, createIdea,
		arg.ID,
		arg.Name,
		arg.ProjectID,
		arg.Description,
		arg.Tags,
		arg.State,
		arg.ReferenceNotes,
	)
	var i Idea
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.Description,
		&i.Tags,
		&i.State,
		&i.ReferenceNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIdea = `-- name: DeleteIdea :exec
DELETE FROM ideas WHERE id = ?
`

func (q *Queries) DeleteIdea(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteIdea, id)
	return err
}

const getIdea = `-- name: GetIdea :one
SELECT id, name, project_id, description, tags, state, reference_notes, created_at, updated_at FROM ideas WHERE id = ? LIMIT 1
`

func (q *Queries) GetIdea(ctx context.Context, id string) (Idea, error) {
	row := q.db.QueryRowContext(ctx, getIdea, id)
	var i Idea
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.Description,
		&i.Tags,
		&i.State,
		&i.ReferenceNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIdeas = `-- name: ListIdeas :many
SELECT id, name, project_id, description, tags, state, reference_notes, created_at, updated_at FROM ideas ORDER BY name ASC
`

func (q *Queries) ListIdeas(ctx context.Context) ([]Idea, error) {
	rows, err := q.db.QueryContext(ctx, listIdeas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Idea
	for rows.Next() {
		var i Idea
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectID,
			&i.Description,
			&i.Tags,
			&i.State,
			&i.ReferenceNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdeasByProject = `-- name: ListIdeasByProject :many
SELECT id, name, project_id, description, tags, state, reference_notes, created_at, updated_at FROM ideas WHERE project_id = ? ORDER BY name ASC
`

func (q *Queries) ListIdeasByProject(ctx context.Context, projectID string) ([]Idea, error) {
	rows, err := q.db.QueryContext(ctx, listIdeasByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Idea
	for rows.Next() {
		var i Idea
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectID,
			&i.Description,
			&i.Tags,
			&i.State,
			&i.ReferenceNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIdea = `-- name: UpdateIdea :one
UPDATE ideas
SET
  name = COALESCE(?1, name),
  description = COALESCE(?2, description),
  tags = COALESCE(?3, tags),
  state = COALESCE(?4, state),
  reference_notes = COALESCE(?5, reference_notes)
WHERE id = ?6
RETURNING id, name, project_id, description, tags, state, reference_notes, created_at, updated_at
`

type UpdateIdeaParams struct {
	Name           sql.NullString `json:"name"`
	Description    sql.NullString `json:"description"`
	Tags           sql.NullString `json:"tags"`
	State          sql.NullString `json:"state"`
	ReferenceNotes sql.NullString `json:"reference_notes"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateIdea(ctx context.Context, arg UpdateIdeaParams) (Idea, error) {
	row := q.db.QueryRowContext(ctx, updateIdea,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.State,
		arg.ReferenceNotes,
		arg.ID,
	)
	var i Idea
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.Description,
		&i.Tags,
		&i.State,
		&i.ReferenceNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
