// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Collection struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Tags        sql.NullString `json:"tags"`
	State       string         `json:"state"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type CollectionTrack struct {
	ID           string    `json:"id"`
	CollectionID string    `json:"collection_id"`
	TrackID      string    `json:"track_id"`
	AddedAt      time.Time `json:"added_at"`
}

type Idea struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	ProjectID      string         `json:"project_id"`
	Description    sql.NullString `json:"description"`
	Tags           sql.NullString `json:"tags"`
	State          string         `json:"state"`
	ReferenceNotes sql.NullString `json:"reference_notes"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type Project struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	CollectionID sql.NullString `json:"collection_id"`
	Tags         sql.NullString `json:"tags"`
	State        string         `json:"state"`
	Mood         sql.NullString `json:"mood"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Song struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	IdeaID      string         `json:"idea_id"`
	Description sql.NullString `json:"description"`
	Tags        sql.NullString `json:"tags"`
	State       string         `json:"state"`
	Version     sql.NullString `json:"version"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Track struct {
	ID         string         `json:"id"`
	SongID     sql.NullString `json:"song_id"`
	SourceType string         `json:"source_type"`
	FilePath   string         `json:"file_path"`
	SunoID     sql.NullString `json:"suno_id"`
	UdioID     sql.NullString `json:"udio_id"`
	ImagePath  sql.NullString `json:"image_path"`
	Title      string         `json:"title"`
	DurationMs sql.NullInt64  `json:"duration_ms"`
	StyleDesc  sql.NullString `json:"style_desc"`
	Rating     sql.NullInt64  `json:"rating"`
	IsTrash    bool           `json:"is_trash"`
	IsDeleted  bool           `json:"is_deleted"`
	ArtistTags sql.NullString `json:"artist_tags"`
	AlbumTags  sql.NullString `json:"album_tags"`
	GenreTags  sql.NullString `json:"genre_tags"`
	MoodTags   sql.NullString `json:"mood_tags"`
	Tags       sql.NullString `json:"tags"`
	Metadata   sql.NullString `json:"metadata"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type TrackComment struct {
	TrackID   string         `json:"track_id"`
	General   sql.NullString `json:"general"`
	Pluses    sql.NullString `json:"pluses"`
	Minuses   sql.NullString `json:"minuses"`
	Blockers  sql.NullString `json:"blockers"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
