// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, name, description, collection_id, tags, state, mood)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, collection_id, tags, state, mood, created_at, updated_at
`

type CreateProjectParams struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	CollectionID sql.NullString `json:"collection_id"`
	Tags         sql.NullString `json:"tags"`
	State        string         `json:"state"`
	Mood         sql.NullString `json:"mood"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CollectionID,
		arg.Tags,
		arg.State,
		arg.Mood,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CollectionID,
		&i.Tags,
		&i.State,
		&i.Mood,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, collection_id, tags, state, mood, created_at, updated_at FROM projects WHERE id = ? LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CollectionID,
		&i.Tags,
		&i.State,
		&i.Mood,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, description, collection_id, tags, state, mood, created_at, updated_at FROM projects ORDER BY name ASC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CollectionID,
			&i.Tags,
			&i.State,
			&i.Mood,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByCollection = `-- name: ListProjectsByCollection :many
SELECT id, name, description, collection_id, tags, state, mood, created_at, updated_at FROM projects WHERE collection_id = ? ORDER BY name ASC
`

func (q *Queries) ListProjectsByCollection(ctx context.Context, collectionID sql.NullString) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CollectionID,
			&i.Tags,
			&i.State,
			&i.Mood,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
  name = COALESCE(?1, name),
  description = COALESCE(?2, description),
  collection_id = COALESCE(?3, collection_id),
  tags = COALESCE(?4, tags),
  state = COALESCE(?5, state),
  mood = COALESCE(?6, mood)
WHERE id = ?7
RETURNING id, name, description, collection_id, tags, state, mood, created_at, updated_at
`

type UpdateProjectParams struct {
	Name         sql.NullString `json:"name"`
	Description  sql.NullString `json:"description"`
	CollectionID sql.NullString `json:"collection_id"`
	Tags         sql.NullString `json:"tags"`
	State        sql.NullString `json:"state"`
	Mood         sql.NullString `json:"mood"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.CollectionID,
		arg.Tags,
		arg.State,
		arg.Mood,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CollectionID,
		&i.Tags,
		&i.State,
		&i.Mood,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
