// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddTrackToCollection(ctx context.Context, arg AddTrackToCollectionParams) (CollectionTrack, error)
	BulkUpdateTracksSong(ctx context.Context, arg BulkUpdateTracksSongParams) error
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error)
	CreateIdea(ctx context.Context, arg CreateIdeaParams) (Idea, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSong(ctx context.Context, arg CreateSongParams) (Song, error)
	CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error)
	CreateTrackComment(ctx context.Context, arg CreateTrackCommentParams) (TrackComment, error)
	DeleteAllTracks(ctx context.Context) error
	DeleteCollection(ctx context.Context, id string) error
	DeleteIdea(ctx context.Context, id string) error
	DeleteProject(ctx context.Context, id string) error
	DeleteSong(ctx context.Context, id string) error
	DeleteTrack(ctx context.Context, id string) error
	DeleteTrackComment(ctx context.Context, trackID string) error
	GetCollection(ctx context.Context, id string) (Collection, error)
	GetCollectionTracks(ctx context.Context, collectionID string) ([]Track, error)
	GetIdea(ctx context.Context, id string) (Idea, error)
	GetProject(ctx context.Context, id string) (Project, error)
	GetSong(ctx context.Context, id string) (Song, error)
	GetTrack(ctx context.Context, id string) (Track, error)
	GetTrackByFilePath(ctx context.Context, filePath string) (Track, error)
	GetTrackCollections(ctx context.Context, trackID string) ([]Collection, error)
	GetTrackComment(ctx context.Context, trackID string) (TrackComment, error)
	IsTrackInAnyCollection(ctx context.Context, trackID string) (int64, error)
	ListCollections(ctx context.Context) ([]Collection, error)
	ListIdeas(ctx context.Context) ([]Idea, error)
	ListIdeasByProject(ctx context.Context, projectID string) ([]Idea, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListProjectsByCollection(ctx context.Context, collectionID sql.NullString) ([]Project, error)
	ListSongs(ctx context.Context) ([]Song, error)
	ListSongsByIdea(ctx context.Context, ideaID string) ([]Song, error)
	// WORKSPACE QUERIES (file path based)
	ListSunoTracksInFolder(ctx context.Context, filePath string) ([]Track, error)
	ListTracks(ctx context.Context) ([]Track, error)
	ListTracksByRating(ctx context.Context, rating sql.NullInt64) ([]Track, error)
	ListTracksBySong(ctx context.Context, songID sql.NullString) ([]Track, error)
	ListTracksBySource(ctx context.Context, sourceType string) ([]Track, error)
	ListTrashedTracks(ctx context.Context) ([]Track, error)
	ListUdioTracksInPath(ctx context.Context, filePath string) ([]Track, error)
	ListUnassignedTracks(ctx context.Context) ([]Track, error)
	RemoveTrackFromCollection(ctx context.Context, arg RemoveTrackFromCollectionParams) error
	SoftDeleteTrack(ctx context.Context, id string) error
	UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error)
	UpdateIdea(ctx context.Context, arg UpdateIdeaParams) (Idea, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error)
	UpdateTrack(ctx context.Context, arg UpdateTrackParams) (Track, error)
	UpdateTrackComment(ctx context.Context, arg UpdateTrackCommentParams) (TrackComment, error)
	UpdateTrackRating(ctx context.Context, arg UpdateTrackRatingParams) (Track, error)
	UpdateTrackSong(ctx context.Context, arg UpdateTrackSongParams) (Track, error)
	UpdateTrackTrash(ctx context.Context, arg UpdateTrackTrashParams) (Track, error)
	UpsertTrackComment(ctx context.Context, arg UpsertTrackCommentParams) (TrackComment, error)
}

var _ Querier = (*Queries)(nil)
