// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: songs.sql

package db

import (
	"context"
	"database/sql"
)

const createSong = `-- name: CreateSong :one
INSERT INTO songs (id, name, idea_id, description, tags, state, version)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, idea_id, description, tags, state, version, created_at, updated_at
`

type CreateSongParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	IdeaID      string         `json:"idea_id"`
	Description sql.NullString `json:"description"`
	Tags        sql.NullString `json:"tags"`
	State       string         `json:"state"`
	Version     sql.NullString `json:"version"`
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRowContext(ctx, createSong,
		arg.ID,
		arg.Name,
		arg.IdeaID,
		arg.Description,
		arg.Tags,
		arg.State,
		arg.Version,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IdeaID,
		&i.Description,
		&i.Tags,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSong = `-- name: DeleteSong :exec
DELETE FROM songs WHERE id = ?
`

func (q *Queries) DeleteSong(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSong, id)
	return err
}

const getSong = `-- name: GetSong :one
SELECT id, name, idea_id, description, tags, state, version, created_at, updated_at FROM songs WHERE id = ? LIMIT 1
`

func (q *Queries) GetSong(ctx context.Context, id string) (Song, error) {
	row := q.db.QueryRowContext(ctx, getSong, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IdeaID,
		&i.Description,
		&i.Tags,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSongs = `-- name: ListSongs :many
SELECT id, name, idea_id, description, tags, state, version, created_at, updated_at FROM songs ORDER BY name ASC
`

func (q *Queries) ListSongs(ctx context.Context) ([]Song, error) {
	rows, err := q.db.QueryContext(ctx, listSongs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IdeaID,
			&i.Description,
			&i.Tags,
			&i.State,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongsByIdea = `-- name: ListSongsByIdea :many
SELECT id, name, idea_id, description, tags, state, version, created_at, updated_at FROM songs WHERE idea_id = ? ORDER BY name ASC
`

func (q *Queries) ListSongsByIdea(ctx context.Context, ideaID string) ([]Song, error) {
	rows, err := q.db.QueryContext(ctx, listSongsByIdea, ideaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IdeaID,
			&i.Description,
			&i.Tags,
			&i.State,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSong = `-- name: UpdateSong :one
UPDATE songs
SET
  name = COALESCE(?1, name),
  description = COALESCE(?2, description),
  tags = COALESCE(?3, tags),
  state = COALESCE(?4, state),
  version = COALESCE(?5, version)
WHERE id = ?6
RETURNING id, name, idea_id, description, tags, state, version, created_at, updated_at
`

type UpdateSongParams struct {
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Tags        sql.NullString `json:"tags"`
	State       sql.NullString `json:"state"`
	Version     sql.NullString `json:"version"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error) {
	row := q.db.QueryRowContext(ctx, updateSong,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.State,
		arg.Version,
		arg.ID,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IdeaID,
		&i.Description,
		&i.Tags,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
