// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: track_comments.sql

package db

import (
	"context"
	"database/sql"
)

const createTrackComment = `-- name: CreateTrackComment :one
INSERT INTO track_comments (track_id, general, pluses, minuses, blockers)
VALUES (?, ?, ?, ?, ?)
RETURNING track_id, general, pluses, minuses, blockers, created_at, updated_at
`

type CreateTrackCommentParams struct {
	TrackID  string         `json:"track_id"`
	General  sql.NullString `json:"general"`
	Pluses   sql.NullString `json:"pluses"`
	Minuses  sql.NullString `json:"minuses"`
	Blockers sql.NullString `json:"blockers"`
}

func (q *Queries) CreateTrackComment(ctx context.Context, arg CreateTrackCommentParams) (TrackComment, error) {
	row := q.db.QueryRowContext(ctx, createTrackComment,
		arg.TrackID,
		arg.General,
		arg.Pluses,
		arg.Minuses,
		arg.Blockers,
	)
	var i TrackComment
	err := row.Scan(
		&i.TrackID,
		&i.General,
		&i.Pluses,
		&i.Minuses,
		&i.Blockers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTrackComment = `-- name: DeleteTrackComment :exec
DELETE FROM track_comments WHERE track_id = ?
`

func (q *Queries) DeleteTrackComment(ctx context.Context, trackID string) error {
	_, err := q.db.ExecContext(ctx, deleteTrackComment, trackID)
	return err
}

const getTrackComment = `-- name: GetTrackComment :one
SELECT track_id, general, pluses, minuses, blockers, created_at, updated_at FROM track_comments WHERE track_id = ? LIMIT 1
`

func (q *Queries) GetTrackComment(ctx context.Context, trackID string) (TrackComment, error) {
	row := q.db.QueryRowContext(ctx, getTrackComment, trackID)
	var i TrackComment
	err := row.Scan(
		&i.TrackID,
		&i.General,
		&i.Pluses,
		&i.Minuses,
		&i.Blockers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTrackComment = `-- name: UpdateTrackComment :one
UPDATE track_comments
SET
  general = COALESCE(?1, general),
  pluses = COALESCE(?2, pluses),
  minuses = COALESCE(?3, minuses),
  blockers = COALESCE(?4, blockers)
WHERE track_id = ?5
RETURNING track_id, general, pluses, minuses, blockers, created_at, updated_at
`

type UpdateTrackCommentParams struct {
	General  sql.NullString `json:"general"`
	Pluses   sql.NullString `json:"pluses"`
	Minuses  sql.NullString `json:"minuses"`
	Blockers sql.NullString `json:"blockers"`
	TrackID  string         `json:"track_id"`
}

func (q *Queries) UpdateTrackComment(ctx context.Context, arg UpdateTrackCommentParams) (TrackComment, error) {
	row := q.db.QueryRowContext(ctx, updateTrackComment,
		arg.General,
		arg.Pluses,
		arg.Minuses,
		arg.Blockers,
		arg.TrackID,
	)
	var i TrackComment
	err := row.Scan(
		&i.TrackID,
		&i.General,
		&i.Pluses,
		&i.Minuses,
		&i.Blockers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTrackComment = `-- name: UpsertTrackComment :one
INSERT INTO track_comments (track_id, general, pluses, minuses, blockers)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(track_id) DO UPDATE SET
  general = excluded.general,
  pluses = excluded.pluses,
  minuses = excluded.minuses,
  blockers = excluded.blockers,
  updated_at = CURRENT_TIMESTAMP
RETURNING track_id, general, pluses, minuses, blockers, created_at, updated_at
`

type UpsertTrackCommentParams struct {
	TrackID  string         `json:"track_id"`
	General  sql.NullString `json:"general"`
	Pluses   sql.NullString `json:"pluses"`
	Minuses  sql.NullString `json:"minuses"`
	Blockers sql.NullString `json:"blockers"`
}

func (q *Queries) UpsertTrackComment(ctx context.Context, arg UpsertTrackCommentParams) (TrackComment, error) {
	row := q.db.QueryRowContext(ctx, upsertTrackComment,
		arg.TrackID,
		arg.General,
		arg.Pluses,
		arg.Minuses,
		arg.Blockers,
	)
	var i TrackComment
	err := row.Scan(
		&i.TrackID,
		&i.General,
		&i.Pluses,
		&i.Minuses,
		&i.Blockers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
