/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const api: typeof import('./api/apiClient').api
  const apiClient: typeof import('./api/apiClient').apiClient
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createItem: typeof import('./api/itemApi').createItem
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const del: typeof import('./api/apiClient').del
  const deleteItem: typeof import('./api/itemApi').deleteItem
  const effectScope: typeof import('vue').effectScope
  const formatDate: typeof import('./utils/helpers').formatDate
  const get: typeof import('./api/apiClient').get
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getItemBySlug: typeof import('./api/itemApi').getItemBySlug
  const getItemTree: typeof import('./api/itemApi').getItemTree
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const itemKeys: typeof import('./composables/useItemsApi').itemKeys
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const ofetch: typeof import('ofetch').ofetch
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const patch: typeof import('./api/apiClient').patch
  const post: typeof import('./api/apiClient').post
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const slugify: typeof import('./utils/slugify').slugify
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const updateItem: typeof import('./api/itemApi').updateItem
  const useAddItem: typeof import('./composables/useItemsApi').useAddItem
  const useAttrs: typeof import('vue').useAttrs
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDark: typeof import('@vueuse/core').useDark
  const useDeleteItem: typeof import('./composables/useItemsApi').useDeleteItem
  const useForm: typeof import('@tanstack/vue-form').useForm
  const useId: typeof import('vue').useId
  const useItemDetail: typeof import('./composables/useItemsApi').useItemDetail
  const useItemFilters: typeof import('./composables/useItemFilters').useItemFilters
  const useItemStore: typeof import('./stores/itemStore').useItemStore
  const useItemTree: typeof import('./composables/useItemsApi').useItemTree
  const useLink: typeof import('vue-router').useLink
  const useModel: typeof import('vue').useModel
  const useMutation: typeof import('@tanstack/vue-query').useMutation
  const useQuery: typeof import('@tanstack/vue-query').useQuery
  const useQueryClient: typeof import('@tanstack/vue-query').useQueryClient
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useStorage: typeof import('@vueuse/core').useStorage
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useThemeUpdater: typeof import('./composables/useThemeUpdater').useThemeUpdater
  const useToggle: typeof import('@vueuse/core').useToggle
  const useUiStore: typeof import('./stores/uiStore').useUiStore
  const useUpdateItem: typeof import('./composables/useItemsApi').useUpdateItem
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { FilterOptions } from './composables/useItemFilters'
  import('./composables/useItemFilters')
  // @ts-ignore
  export type { Priority, NotificationType, SingleCategory, Item, Category, ItemTree, CreateItemPayload, UpdateItemPayload, ApiResponse, ApiErrorData, Result } from './types/index'
  import('./types/index')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly api: UnwrapRef<typeof import('./api/apiClient')['api']>
    readonly apiClient: UnwrapRef<typeof import('./api/apiClient')['apiClient']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createItem: UnwrapRef<typeof import('./api/itemApi')['createItem']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly del: UnwrapRef<typeof import('./api/apiClient')['del']>
    readonly deleteItem: UnwrapRef<typeof import('./api/itemApi')['deleteItem']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly formatDate: UnwrapRef<typeof import('./utils/helpers')['formatDate']>
    readonly get: UnwrapRef<typeof import('./api/apiClient')['get']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getItemBySlug: UnwrapRef<typeof import('./api/itemApi')['getItemBySlug']>
    readonly getItemTree: UnwrapRef<typeof import('./api/itemApi')['getItemTree']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly itemKeys: UnwrapRef<typeof import('./composables/useItemsApi')['itemKeys']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly ofetch: UnwrapRef<typeof import('ofetch')['ofetch']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly patch: UnwrapRef<typeof import('./api/apiClient')['patch']>
    readonly post: UnwrapRef<typeof import('./api/apiClient')['post']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly slugify: UnwrapRef<typeof import('./utils/slugify')['slugify']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly updateItem: UnwrapRef<typeof import('./api/itemApi')['updateItem']>
    readonly useAddItem: UnwrapRef<typeof import('./composables/useItemsApi')['useAddItem']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDark: UnwrapRef<typeof import('@vueuse/core')['useDark']>
    readonly useDeleteItem: UnwrapRef<typeof import('./composables/useItemsApi')['useDeleteItem']>
    readonly useForm: UnwrapRef<typeof import('@tanstack/vue-form')['useForm']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useItemDetail: UnwrapRef<typeof import('./composables/useItemsApi')['useItemDetail']>
    readonly useItemFilters: UnwrapRef<typeof import('./composables/useItemFilters')['useItemFilters']>
    readonly useItemStore: UnwrapRef<typeof import('./stores/itemStore')['useItemStore']>
    readonly useItemTree: UnwrapRef<typeof import('./composables/useItemsApi')['useItemTree']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useMutation: UnwrapRef<typeof import('@tanstack/vue-query')['useMutation']>
    readonly useQuery: UnwrapRef<typeof import('@tanstack/vue-query')['useQuery']>
    readonly useQueryClient: UnwrapRef<typeof import('@tanstack/vue-query')['useQueryClient']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useStorage: UnwrapRef<typeof import('@vueuse/core')['useStorage']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useThemeUpdater: UnwrapRef<typeof import('./composables/useThemeUpdater')['useThemeUpdater']>
    readonly useToggle: UnwrapRef<typeof import('@vueuse/core')['useToggle']>
    readonly useUiStore: UnwrapRef<typeof import('./stores/uiStore')['useUiStore']>
    readonly useUpdateItem: UnwrapRef<typeof import('./composables/useItemsApi')['useUpdateItem']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}