/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./components/ui/alert-dialog/AlertDialog.vue')['default']
    AlertDialogAction: typeof import('./components/ui/alert-dialog/AlertDialogAction.vue')['default']
    AlertDialogCancel: typeof import('./components/ui/alert-dialog/AlertDialogCancel.vue')['default']
    AlertDialogContent: typeof import('./components/ui/alert-dialog/AlertDialogContent.vue')['default']
    AlertDialogDescription: typeof import('./components/ui/alert-dialog/AlertDialogDescription.vue')['default']
    AlertDialogFooter: typeof import('./components/ui/alert-dialog/AlertDialogFooter.vue')['default']
    AlertDialogHeader: typeof import('./components/ui/alert-dialog/AlertDialogHeader.vue')['default']
    AlertDialogTitle: typeof import('./components/ui/alert-dialog/AlertDialogTitle.vue')['default']
    AlertDialogTrigger: typeof import('./components/ui/alert-dialog/AlertDialogTrigger.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    Badge: typeof import('./components/ui/badge/Badge.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    Card: typeof import('./components/ui/card/Card.vue')['default']
    CardAction: typeof import('./components/ui/card/CardAction.vue')['default']
    CardContent: typeof import('./components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./components/ui/card/CardTitle.vue')['default']
    Checkbox: typeof import('./components/ui/checkbox/Checkbox.vue')['default']
    Dialog: typeof import('./components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./components/ui/dialog/DialogHeader.vue')['default']
    DialogOverlay: typeof import('./components/ui/dialog/DialogOverlay.vue')['default']
    DialogScrollContent: typeof import('./components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./components/ui/dialog/DialogTrigger.vue')['default']
    FilterBar: typeof import('./components/layout/FilterBar.vue')['default']
    IconLucideMoon: typeof import('~icons/lucide/moon')['default']
    IconLucidePencil: typeof import('~icons/lucide/pencil')['default']
    IconLucideSun: typeof import('~icons/lucide/sun')['default']
    IconLucideTrash2: typeof import('~icons/lucide/trash2')['default']
    Input: typeof import('./components/ui/input/Input.vue')['default']
    ItemForm: typeof import('./components/items/ItemForm.vue')['default']
    ItemItem: typeof import('./components/items/ItemItem.vue')['default']
    Label: typeof import('./components/ui/label/Label.vue')['default']
    RadioGroup: typeof import('./components/ui/radio-group/RadioGroup.vue')['default']
    RadioGroupItem: typeof import('./components/ui/radio-group/RadioGroupItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/ui/select/Select.vue')['default']
    SelectContent: typeof import('./components/ui/select/SelectContent.vue')['default']
    SelectGroup: typeof import('./components/ui/select/SelectGroup.vue')['default']
    SelectItem: typeof import('./components/ui/select/SelectItem.vue')['default']
    SelectItemText: typeof import('./components/ui/select/SelectItemText.vue')['default']
    SelectLabel: typeof import('./components/ui/select/SelectLabel.vue')['default']
    SelectScrollDownButton: typeof import('./components/ui/select/SelectScrollDownButton.vue')['default']
    SelectScrollUpButton: typeof import('./components/ui/select/SelectScrollUpButton.vue')['default']
    SelectSeparator: typeof import('./components/ui/select/SelectSeparator.vue')['default']
    SelectTrigger: typeof import('./components/ui/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./components/ui/select/SelectValue.vue')['default']
    Separator: typeof import('./components/ui/separator/Separator.vue')['default']
    Sonner: typeof import('./components/ui/sonner/Sonner.vue')['default']
    TopBar: typeof import('./components/layout/TopBar.vue')['default']
  }
}
