// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Item struct {
	ID          string         `json:"id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Text        sql.NullString `json:"text"`
	IsCompleted bool           `json:"is_completed"`
	Priority    string         `json:"priority"`
	Tags        sql.NullString `json:"tags"`
	Categories  string         `json:"categories"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}
