// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	DeleteItem(ctx context.Context, id string) error
	GetAllItems(ctx context.Context) ([]Item, error)
	GetItem(ctx context.Context, arg GetItemParams) (Item, error)
	GetItemByID(ctx context.Context, id string) (Item, error)
	GetItemTree(ctx context.Context) ([]GetItemTreeRow, error)
	GetItemsByCategory(ctx context.Context, categories string) ([]Item, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error)
}

var _ Querier = (*Queries)(nil)
